package pqmagic

/*






#include <pqmagic_api.h>
*/
import "C"

const (
	MlDsa44PublicKeyBytes = C.ML_DSA_44_PUBLICKEYBYTES
	MlDsa44SecretKeyBytes = C.ML_DSA_44_SECRETKEYBYTES
	MlDsa44SignatureBytes = C.ML_DSA_44_SIGBYTES

	MlDsa65PublicKeyBytes = C.ML_DSA_65_PUBLICKEYBYTES
	MlDsa65SecretKeyBytes = C.ML_DSA_65_SECRETKEYBYTES
	MlDsa65SignatureBytes = C.ML_DSA_65_SIGBYTES

	MlDsa87PublicKeyBytes = C.ML_DSA_87_PUBLICKEYBYTES
	MlDsa87SecretKeyBytes = C.ML_DSA_87_SECRETKEYBYTES
	MlDsa87SignatureBytes = C.ML_DSA_87_SIGBYTES
)

const (
	SlhDsaSha2_128fPublicKeyBytes = C.SLH_DSA_SHA2_128f_PUBLICKEYBYTES
	SlhDsaSha2_128fSecretKeyBytes = C.SLH_DSA_SHA2_128f_SECRETKEYBYTES
	SlhDsaSha2_128fSignatureBytes = C.SLH_DSA_SHA2_128f_SIGBYTES
)

const (
	Dilithium2PublicKeyBytes = C.DILITHIUM2_PUBLICKEYBYTES
	Dilithium2SecretKeyBytes = C.DILITHIUM2_SECRETKEYBYTES
	Dilithium2SignatureBytes = C.DILITHIUM2_SIGBYTES

	Dilithium3PublicKeyBytes = C.DILITHIUM3_PUBLICKEYBYTES
	Dilithium3SecretKeyBytes = C.DILITHIUM3_SECRETKEYBYTES
	Dilithium3SignatureBytes = C.DILITHIUM3_SIGBYTES

	Dilithium5PublicKeyBytes = C.DILITHIUM5_PUBLICKEYBYTES
	Dilithium5SecretKeyBytes = C.DILITHIUM5_SECRETKEYBYTES
	Dilithium5SignatureBytes = C.DILITHIUM5_SIGBYTES
)

const (
	MlKem512PublicKeyBytes    = C.ML_KEM_512_PUBLICKEYBYTES
	MlKem512SecretKeyBytes    = C.ML_KEM_512_SECRETKEYBYTES
	MlKem512CiphertextBytes   = C.ML_KEM_512_CIPHERTEXTBYTES
	MlKem512SharedSecretBytes = C.ML_KEM_512_SSBYTES

	MlKem768PublicKeyBytes    = C.ML_KEM_768_PUBLICKEYBYTES
	MlKem768SecretKeyBytes    = C.ML_KEM_768_SECRETKEYBYTES
	MlKem768CiphertextBytes   = C.ML_KEM_768_CIPHERTEXTBYTES
	MlKem768SharedSecretBytes = C.ML_KEM_768_SSBYTES

	MlKem1024PublicKeyBytes    = C.ML_KEM_1024_PUBLICKEYBYTES
	MlKem1024SecretKeyBytes    = C.ML_KEM_1024_SECRETKEYBYTES
	MlKem1024CiphertextBytes   = C.ML_KEM_1024_CIPHERTEXTBYTES
	MlKem1024SharedSecretBytes = C.ML_KEM_1024_SSBYTES
)

const (
	Kyber512PublicKeyBytes    = C.KYBER512_PUBLICKEYBYTES
	Kyber512SecretKeyBytes    = C.KYBER512_SECRETKEYBYTES
	Kyber512CiphertextBytes   = C.KYBER512_CIPHERTEXTBYTES
	Kyber512SharedSecretBytes = C.KYBER512_SSBYTES

	Kyber768PublicKeyBytes    = C.KYBER768_PUBLICKEYBYTES
	Kyber768SecretKeyBytes    = C.KYBER768_SECRETKEYBYTES
	Kyber768CiphertextBytes   = C.KYBER768_CIPHERTEXTBYTES
	Kyber768SharedSecretBytes = C.KYBER768_SSBYTES

	Kyber1024PublicKeyBytes    = C.KYBER1024_PUBLICKEYBYTES
	Kyber1024SecretKeyBytes    = C.KYBER1024_SECRETKEYBYTES
	Kyber1024CiphertextBytes   = C.KYBER1024_CIPHERTEXTBYTES
	Kyber1024SharedSecretBytes = C.KYBER1024_SSBYTES
)

const (
	AigisEnc1PublicKeyBytes    = C.AIGIS_ENC_1_PUBLICKEYBYTES
	AigisEnc1SecretKeyBytes    = C.AIGIS_ENC_1_SECRETKEYBYTES
	AigisEnc1CiphertextBytes   = C.AIGIS_ENC_1_CIPHERTEXTBYTES
	AigisEnc1SharedSecretBytes = C.AIGIS_ENC_1_SSBYTES
)

const (
	AigisSig1PublicKeyBytes = C.AIGIS_SIG1_PUBLICKEYBYTES
	AigisSig1SecretKeyBytes = C.AIGIS_SIG1_SECRETKEYBYTES
	AigisSig1SignatureBytes = C.AIGIS_SIG1_SIGBYTES
)

const (
	SphincsASha2_128fPublicKeyBytes = C.SPHINCS_A_SHA2_128f_PUBLICKEYBYTES
	SphincsASha2_128fSecretKeyBytes = C.SPHINCS_A_SHA2_128f_SECRETKEYBYTES
	SphincsASha2_128fSignatureBytes = C.SPHINCS_A_SHA2_128f_SIGBYTES
)

const (
	SlhDsaSha2_128sPublicKeyBytes  = C.SLH_DSA_SHA2_128s_PUBLICKEYBYTES
	SlhDsaSha2_128sSecretKeyBytes  = C.SLH_DSA_SHA2_128s_SECRETKEYBYTES
	SlhDsaSha2_128sSignatureBytes  = C.SLH_DSA_SHA2_128s_SIGBYTES
	SlhDsaSha2_192fPublicKeyBytes  = C.SLH_DSA_SHA2_192f_PUBLICKEYBYTES
	SlhDsaSha2_192fSecretKeyBytes  = C.SLH_DSA_SHA2_192f_SECRETKEYBYTES
	SlhDsaSha2_192fSignatureBytes  = C.SLH_DSA_SHA2_192f_SIGBYTES
	SlhDsaSha2_192sPublicKeyBytes  = C.SLH_DSA_SHA2_192s_PUBLICKEYBYTES
	SlhDsaSha2_192sSecretKeyBytes  = C.SLH_DSA_SHA2_192s_SECRETKEYBYTES
	SlhDsaSha2_192sSignatureBytes  = C.SLH_DSA_SHA2_192s_SIGBYTES
	SlhDsaSha2_256fPublicKeyBytes  = C.SLH_DSA_SHA2_256f_PUBLICKEYBYTES
	SlhDsaSha2_256fSecretKeyBytes  = C.SLH_DSA_SHA2_256f_SECRETKEYBYTES
	SlhDsaSha2_256fSignatureBytes  = C.SLH_DSA_SHA2_256f_SIGBYTES
	SlhDsaSha2_256sPublicKeyBytes  = C.SLH_DSA_SHA2_256s_PUBLICKEYBYTES
	SlhDsaSha2_256sSecretKeyBytes  = C.SLH_DSA_SHA2_256s_SECRETKEYBYTES
	SlhDsaSha2_256sSignatureBytes  = C.SLH_DSA_SHA2_256s_SIGBYTES
	SlhDsaShake128fPublicKeyBytes = C.SLH_DSA_SHAKE_128f_PUBLICKEYBYTES
	SlhDsaShake128fSecretKeyBytes = C.SLH_DSA_SHAKE_128f_SECRETKEYBYTES
	SlhDsaShake128fSignatureBytes = C.SLH_DSA_SHAKE_128f_SIGBYTES
	SlhDsaShake128sPublicKeyBytes = C.SLH_DSA_SHAKE_128s_PUBLICKEYBYTES
	SlhDsaShake128sSecretKeyBytes = C.SLH_DSA_SHAKE_128s_SECRETKEYBYTES
	SlhDsaShake128sSignatureBytes = C.SLH_DSA_SHAKE_128s_SIGBYTES
	SlhDsaShake192fPublicKeyBytes = C.SLH_DSA_SHAKE_192f_PUBLICKEYBYTES
	SlhDsaShake192fSecretKeyBytes = C.SLH_DSA_SHAKE_192f_SECRETKEYBYTES
	SlhDsaShake192fSignatureBytes = C.SLH_DSA_SHAKE_192f_SIGBYTES
	SlhDsaShake192sPublicKeyBytes = C.SLH_DSA_SHAKE_192s_PUBLICKEYBYTES
	SlhDsaShake192sSecretKeyBytes = C.SLH_DSA_SHAKE_192s_SECRETKEYBYTES
	SlhDsaShake192sSignatureBytes = C.SLH_DSA_SHAKE_192s_SIGBYTES
	SlhDsaShake256fPublicKeyBytes = C.SLH_DSA_SHAKE_256f_PUBLICKEYBYTES
	SlhDsaShake256fSecretKeyBytes = C.SLH_DSA_SHAKE_256f_SECRETKEYBYTES
	SlhDsaShake256fSignatureBytes = C.SLH_DSA_SHAKE_256f_SIGBYTES
	SlhDsaShake256sPublicKeyBytes = C.SLH_DSA_SHAKE_256s_PUBLICKEYBYTES
	SlhDsaShake256sSecretKeyBytes = C.SLH_DSA_SHAKE_256s_SECRETKEYBYTES
	SlhDsaShake256sSignatureBytes = C.SLH_DSA_SHAKE_256s_SIGBYTES
	SlhDsaSm3_128fPublicKeyBytes  = C.SLH_DSA_SM3_128f_PUBLICKEYBYTES  
	SlhDsaSm3_128fSecretKeyBytes  = C.SLH_DSA_SM3_128f_SECRETKEYBYTES
	SlhDsaSm3_128fSignatureBytes  = C.SLH_DSA_SM3_128f_SIGBYTES
	SlhDsaSm3_128sPublicKeyBytes  = C.SLH_DSA_SM3_128s_PUBLICKEYBYTES
	SlhDsaSm3_128sSecretKeyBytes  = C.SLH_DSA_SM3_128s_SECRETKEYBYTES
	SlhDsaSm3_128sSignatureBytes  = C.SLH_DSA_SM3_128s_SIGBYTES
)

const (
	AigisSig2PublicKeyBytes = C.AIGIS_SIG2_PUBLICKEYBYTES
	AigisSig2SecretKeyBytes = C.AIGIS_SIG2_SECRETKEYBYTES
	AigisSig2SignatureBytes = C.AIGIS_SIG2_SIGBYTES
	AigisSig3PublicKeyBytes = C.AIGIS_SIG3_PUBLICKEYBYTES
	AigisSig3SecretKeyBytes = C.AIGIS_SIG3_SECRETKEYBYTES
	AigisSig3SignatureBytes = C.AIGIS_SIG3_SIGBYTES
)

const (
	SphincsASha2_128sPublicKeyBytes  = C.SPHINCS_A_SHA2_128s_PUBLICKEYBYTES
	SphincsASha2_128sSecretKeyBytes  = C.SPHINCS_A_SHA2_128s_SECRETKEYBYTES
	SphincsASha2_128sSignatureBytes  = C.SPHINCS_A_SHA2_128s_SIGBYTES
	SphincsASha2_192fPublicKeyBytes  = C.SPHINCS_A_SHA2_192f_PUBLICKEYBYTES
	SphincsASha2_192fSecretKeyBytes  = C.SPHINCS_A_SHA2_192f_SECRETKEYBYTES
	SphincsASha2_192fSignatureBytes  = C.SPHINCS_A_SHA2_192f_SIGBYTES
	SphincsASha2_192sPublicKeyBytes  = C.SPHINCS_A_SHA2_192s_PUBLICKEYBYTES
	SphincsASha2_192sSecretKeyBytes  = C.SPHINCS_A_SHA2_192s_SECRETKEYBYTES
	SphincsASha2_192sSignatureBytes  = C.SPHINCS_A_SHA2_192s_SIGBYTES
	SphincsASha2_256fPublicKeyBytes  = C.SPHINCS_A_SHA2_256f_PUBLICKEYBYTES
	SphincsASha2_256fSecretKeyBytes  = C.SPHINCS_A_SHA2_256f_SECRETKEYBYTES
	SphincsASha2_256fSignatureBytes  = C.SPHINCS_A_SHA2_256f_SIGBYTES
	SphincsASha2_256sPublicKeyBytes  = C.SPHINCS_A_SHA2_256s_PUBLICKEYBYTES
	SphincsASha2_256sSecretKeyBytes  = C.SPHINCS_A_SHA2_256s_SECRETKEYBYTES
	SphincsASha2_256sSignatureBytes  = C.SPHINCS_A_SHA2_256s_SIGBYTES
	SphincsAShake128fPublicKeyBytes = C.SPHINCS_A_SHAKE_128f_PUBLICKEYBYTES
	SphincsAShake128fSecretKeyBytes = C.SPHINCS_A_SHAKE_128f_SECRETKEYBYTES
	SphincsAShake128fSignatureBytes = C.SPHINCS_A_SHAKE_128f_SIGBYTES
	SphincsAShake128sPublicKeyBytes = C.SPHINCS_A_SHAKE_128s_PUBLICKEYBYTES
	SphincsAShake128sSecretKeyBytes = C.SPHINCS_A_SHAKE_128s_SECRETKEYBYTES
	SphincsAShake128sSignatureBytes = C.SPHINCS_A_SHAKE_128s_SIGBYTES
	SphincsAShake192fPublicKeyBytes = C.SPHINCS_A_SHAKE_192f_PUBLICKEYBYTES
	SphincsAShake192fSecretKeyBytes = C.SPHINCS_A_SHAKE_192f_SECRETKEYBYTES
	SphincsAShake192fSignatureBytes = C.SPHINCS_A_SHAKE_192f_SIGBYTES
	SphincsAShake192sPublicKeyBytes = C.SPHINCS_A_SHAKE_192s_PUBLICKEYBYTES
	SphincsAShake192sSecretKeyBytes = C.SPHINCS_A_SHAKE_192s_SECRETKEYBYTES
	SphincsAShake192sSignatureBytes = C.SPHINCS_A_SHAKE_192s_SIGBYTES
	SphincsAShake256fPublicKeyBytes = C.SPHINCS_A_SHAKE_256f_PUBLICKEYBYTES
	SphincsAShake256fSecretKeyBytes = C.SPHINCS_A_SHAKE_256f_SECRETKEYBYTES
	SphincsAShake256fSignatureBytes = C.SPHINCS_A_SHAKE_256f_SIGBYTES
	SphincsAShake256sPublicKeyBytes = C.SPHINCS_A_SHAKE_256s_PUBLICKEYBYTES
	SphincsAShake256sSecretKeyBytes = C.SPHINCS_A_SHAKE_256s_SECRETKEYBYTES
	SphincsAShake256sSignatureBytes = C.SPHINCS_A_SHAKE_256s_SIGBYTES
	SphincsASm3_128fPublicKeyBytes  = C.SPHINCS_A_SM3_128f_PUBLICKEYBYTES 
	SphincsASm3_128fSecretKeyBytes  = C.SPHINCS_A_SM3_128f_SECRETKEYBYTES
	SphincsASm3_128fSignatureBytes  = C.SPHINCS_A_SM3_128f_SIGBYTES
	SphincsASm3_128sPublicKeyBytes  = C.SPHINCS_A_SM3_128s_PUBLICKEYBYTES
	SphincsASm3_128sSecretKeyBytes  = C.SPHINCS_A_SM3_128s_SECRETKEYBYTES
	SphincsASm3_128sSignatureBytes  = C.SPHINCS_A_SM3_128s_SIGBYTES
)

const (
	AigisEnc2PublicKeyBytes    = C.AIGIS_ENC_2_PUBLICKEYBYTES
	AigisEnc2SecretKeyBytes    = C.AIGIS_ENC_2_SECRETKEYBYTES
	AigisEnc2CiphertextBytes   = C.AIGIS_ENC_2_CIPHERTEXTBYTES
	AigisEnc2SharedSecretBytes = C.AIGIS_ENC_2_SSBYTES
	AigisEnc3PublicKeyBytes    = C.AIGIS_ENC_3_PUBLICKEYBYTES
	AigisEnc3SecretKeyBytes    = C.AIGIS_ENC_3_SECRETKEYBYTES
	AigisEnc3CiphertextBytes   = C.AIGIS_ENC_3_CIPHERTEXTBYTES
	AigisEnc3SharedSecretBytes = C.AIGIS_ENC_3_SSBYTES
	AigisEnc4PublicKeyBytes    = C.AIGIS_ENC_4_PUBLICKEYBYTES
	AigisEnc4SecretKeyBytes    = C.AIGIS_ENC_4_SECRETKEYBYTES
	AigisEnc4CiphertextBytes   = C.AIGIS_ENC_4_CIPHERTEXTBYTES
	AIGISEnc4SharedSecretBytes = C.AIGIS_ENC_4_SSBYTES 
)
